# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LicksDistribution.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LickDistribution(object):
    def setupUi(self, LickDistribution):
        LickDistribution.setObjectName("LickDistribution")
        LickDistribution.resize(767, 433)
        self.VisuLicksStatistics = QtWidgets.QGroupBox(LickDistribution)
        self.VisuLicksStatistics.setGeometry(QtCore.QRect(20, 10, 731, 401))
        self.VisuLicksStatistics.setObjectName("VisuLicksStatistics")

        self.retranslateUi(LickDistribution)
        QtCore.QMetaObject.connectSlotsByName(LickDistribution)

    def retranslateUi(self, LickDistribution):
        _translate = QtCore.QCoreApplication.translate
        LickDistribution.setWindowTitle(_translate("LickDistribution", "Dialog"))
        self.VisuLicksStatistics.setTitle(_translate("LickDistribution", "Licks distribution"))
