# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Manipulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manipulator(object):
    def setupUi(self, Manipulator):
        Manipulator.setObjectName("Manipulator")
        Manipulator.resize(400, 300)

        self.retranslateUi(Manipulator)
        QtCore.QMetaObject.connectSlotsByName(Manipulator)

    def retranslateUi(self, Manipulator):
        _translate = QtCore.QCoreApplication.translate
        Manipulator.setWindowTitle(_translate("Manipulator", "Manipulator"))
