# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MotorStage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MotorStage(object):
    def setupUi(self, MotorStage):
        MotorStage.setObjectName("MotorStage")
        MotorStage.resize(400, 300)

        self.retranslateUi(MotorStage)
        QtCore.QMetaObject.connectSlotsByName(MotorStage)

    def retranslateUi(self, MotorStage):
        _translate = QtCore.QCoreApplication.translate
        MotorStage.setWindowTitle(_translate("MotorStage", "Motor Stage"))
