# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Optogenetics.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Optogenetics(object):
    def setupUi(self, Optogenetics):
        Optogenetics.setObjectName("Optogenetics")
        Optogenetics.resize(400, 300)
        self.label = QtWidgets.QLabel(Optogenetics)
        self.label.setGeometry(QtCore.QRect(40, 40, 47, 13))
        self.label.setObjectName("label")

        self.retranslateUi(Optogenetics)
        QtCore.QMetaObject.connectSlotsByName(Optogenetics)

    def retranslateUi(self, Optogenetics):
        _translate = QtCore.QCoreApplication.translate
        Optogenetics.setWindowTitle(_translate("Optogenetics", "Optogenetics"))
        self.label.setText(_translate("Optogenetics", "Laser"))
