# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeDistribution.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeDistribution(object):
    def setupUi(self, TimeDistribution):
        TimeDistribution.setObjectName("TimeDistribution")
        TimeDistribution.resize(961, 489)
        self.VisualizeTimeDist = QtWidgets.QGroupBox(TimeDistribution)
        self.VisualizeTimeDist.setGeometry(QtCore.QRect(30, 50, 891, 421))
        self.VisualizeTimeDist.setObjectName("VisualizeTimeDist")

        self.retranslateUi(TimeDistribution)
        QtCore.QMetaObject.connectSlotsByName(TimeDistribution)

    def retranslateUi(self, TimeDistribution):
        _translate = QtCore.QCoreApplication.translate
        TimeDistribution.setWindowTitle(_translate("TimeDistribution", "Dialog"))
        self.VisualizeTimeDist.setTitle(_translate("TimeDistribution", "Simulated results"))
