name: production-merge-action
run-name: create production merge 
on:
    schedule:
    - cron: '0 8 * * 5'
jobs:
    create-production-merge:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: get current date
              id: date
              run: |
                echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
            - run: echo $date
            - run: echo "testing string ${{ env.date }}"
            - name: create pull request
              run: gh pr create -B production_testing -H develop --title "[production merge] ${{ env.date }}" --body 'Created by Github Actions' --assignee alexpiet --reviewer alexpiet --reviewer hanhou --reviewer XX-Yin
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

