name: version increment
run-name: increment foraging gui version
on:
  push:
    branches:
      - main

jobs:
   bump-version:
     uses: AllenNeuralDynamics/.github/.github/workflows/release-bump-version.yml@main
     with:
       default_branch: main # optional, default: main
     secrets:
       repo-token: ${{ secrets.SERVICE_TOKEN }} # required
